# Generated by Django 3.2.7 on 2021-09-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='livro',
            name='emprestimo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
    ]
