# Generated by Django 3.2.6 on 2021-10-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('biblioteca', '0002_auto_20210924_1340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livro',
            table='livro',
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(verbose_name='Data de Entrega')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluno', to='aluno.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='biblioteca.livro')),
            ],
            options={
                'db_table': 'emprestimo',
            },
        ),
    ]
