# Generated by Django 3.2.7 on 2021-10-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20211006_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='emprestimo',
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
