# Generated by Django 3.2.7 on 2021-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_alter_emprestimo_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_criacao',
            field=models.DateTimeField(null=True),
        ),
    ]
